lab8/Src/Frontend/Models/ErrorViewModel.cs
using System;

namespace frontend.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

lab8/Src/Frontend/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using frontend.Models;
using Frontend;
using System.Net.Http;
using System.Net.Http.Headers;
using Frontend.Clients;
using Lib.Http.Client;
using Frontend.Types;
using Frontend.Dtos;

namespace frontend.Controllers
{
    [Route("")]
    [Route("[controller]")]
    public class HomeController : Controller
    {
        BackendClient _backendClient;

        public HomeController(BackendClient backendClient)
        {
            _backendClient = backendClient;
        }

        public IActionResult Index()
        {
            return View();
        }

        [Route("upload")]
        public IActionResult Upload()
        {
            return View();
        }

        [Route("text-details")]
        [HttpGet]
        public async Task<IActionResult> GetTextDetailsAsync(string textId)
        {
            Response<TextProcessingResultDto> response = await _backendClient
                .GetAsync<TextProcessingResultDto>($"api/text/text-processing-result?textId={textId}");
            if (!response.IsSuccessStatusCode)
            {
                return Error();
            }

            TextProcessingResultDto textProcessingResultDto = response.Result;

            return View("TextDetails", textProcessingResultDto);
        }

        [Route("upload")]
        [HttpPost]
        public async Task<IActionResult> UploadAsync(string data, RegionType regionType)
        {
            UploadDto uploadDto = new UploadDto {Text = data, RegionType = regionType};
            string textId = (await _backendClient.PostAsync<string, UploadDto>(uploadDto, "api/text")).Result;
            return RedirectToAction("GetTextDetailsAsync", new { textId = textId });
        }

        [HttpGet("Error")]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

lab8/Src/Frontend/Controllers/StatisticsController.cs
using System.Threading.Tasks;
using Frontend.Clients;
using Frontend.Dtos;
using Lib.Http.Client;
using Microsoft.AspNetCore.Mvc;

namespace Frontend.Controllers
{
    [Route("[controller]")]
    public class StatisticsController: Controller
    {
        private readonly BackendClient _backendClient;
        public StatisticsController(BackendClient backendClient)
        {
            _backendClient = backendClient;
        }

        [HttpGet("")]
        public async Task<IActionResult> Index()
        {
            Response<TextStatisticDto> textStatisticResponse = await _backendClient.GetAsync<TextStatisticDto>("api/text/statistic");

            return View(textStatisticResponse.Result);
        }
    }
}

lab8/Src/Frontend/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<div class="row body-content">
    <p style="margin-top: 5px;">Hello</p>
</div>

lab8/Src/Frontend/Views/Home/TextDetails.cshtml
@{
    ViewData["Title"] = "Text details";
    @model TextProcessingResultDto;
}
<div class="row body-content">
    @if(Model.IsTextProcessingAllowed)
    {
        double rank = @Model.Rank ?? 0;
        <p style="margin-top: 5px;">Ранг: @rank</p>
    }
    else
    {
        <p style="margin-top: 5px;">Количество бесплатных обработок закончилось. Зайдите через минуту</p>
    }
</div>

lab8/Src/Frontend/Views/Home/Upload.cshtml
@{
    ViewData["Title"] = "Upload";
}
<div class="row body-content">
    <form autocomplete="off" class="form" method="POST">
        <div class="form-input">Data: <input name="data" type="text" /></div>
        <p><select name="regionType">
            <option value=@RegionType.Ru>RU</option>
            <option value=@RegionType.Eu>EU</option>
            <option value=@RegionType.Usa>USA</option>
        </select></p>
        <input type="submit" />
    </form>
</div>

lab8/Src/Frontend/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - frontend</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Frontend</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Statistics" asp-action="Index">Statistics</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Upload">Upload</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - Igor Egoshin, PS-32</p>
        </footer>
    </div>

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

lab8/Src/Frontend/Views/Statistics/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
    @model TextStatisticDto;
}
<div class="row body-content">
    @if(Model != null)
    {
        <p>Text number: @Model.TextNum</p>
        <p>High rank part:@Model.HighRankPart</p>
        <p>Average rank:@Math.Round(Model.AvgRank, 2)</p>
        <p>Failure text count:@Model.FailureTextCount</p>
    }
    else
    {
        <p>Пока нет информации для статистики</p>
    }
</div>